language: php

php:
    - 5.6
    - 7.0
    - hhvm

before_script:
    mkdir tests/data
    composer install -n

script:
    phpunit --configuration tests/phpunit.xml --coverage-clover coverage.xml tests